using FluentAssertions;
using StarsAndSteel.Core.Enums;
using StarsAndSteel.Core.Seeding;
using StarsAndSteel.Data.Seeding;

namespace StarsAndSteel.Tests.Seeding;

/// <summary>
/// Smoke tests for <see cref="MapSeeder"/>. These confirm the build pipeline
/// copies <c>shared/map-data.json</c> into the test bin directory, that the
/// JSON shape matches the seeder's expected DTOs, and that the structural
/// invariants required by downstream code (composite-PK ordering, deterministic
/// hashing, graph connectivity) hold.
/// <para/>
/// The map is generated by <c>scripts/build-map.mjs</c> from Natural Earth
/// admin_1 data: 50 US states + 5 Canada blocs + 3 Mexico blocs = 58 provinces,
/// every province <c>ProvinceType.Capital</c> per the user's design call.
/// </summary>
public class MapSeederTests
{
    [Fact]
    public void Load_ReadsRealWorldMapFromSharedJson()
    {
        var data = MapSeeder.Load();

        data.Provinces.Should().HaveCount(58,
            "the real-world map ships with 50 US states + 5 Canada blocs + 3 Mexico blocs");
        data.Adjacencies.Should().NotBeEmpty(
            "the seeded map must have land borders so units can move");

        // Per the user's design: every province is a Capital. PlayerSpawner
        // depends on this — if a non-Capital province slips through the
        // generator, spawn behavior changes silently.
        data.Provinces.Should().OnlyContain(p => p.Type == ProvinceType.Capital,
            "every province on the real-world map is ProvinceType.Capital");

        // Spot-check a known US state to confirm field wiring.
        var california = data.Provinces.SingleOrDefault(p => p.Name == "California");
        california.Should().NotBeNull("California should be one of the 50 US states");
        california!.IsCoastal.Should().BeTrue();
        california.MoneyPerTick.Should().BeGreaterThan(0);
        california.BasePopulation.Should().BeGreaterThan(0);
    }

    [Fact]
    public void Load_PutsSmallerGuidInProvinceA()
    {
        // Composite-PK invariant from docs/03-DATABASE-SCHEMA.md:
        // ProvinceAId < ProvinceBId. Adjacency lookups depend on this; the
        // seeder normalizes on the way out so callers don't have to.
        var data = MapSeeder.Load();

        foreach (var edge in data.Adjacencies)
        {
            edge.ProvinceAId.CompareTo(edge.ProvinceBId)
                .Should().BeLessThan(0,
                    "every adjacency row must satisfy ProvinceAId < ProvinceBId");
        }
    }

    [Fact]
    public void Load_AdjacenciesReferenceKnownProvinces()
    {
        // A typo or stale id in map-data.json would dangle an adjacency. EF
        // would reject it at insert time with an opaque FK error; catching it
        // here makes the failure obvious.
        var data = MapSeeder.Load();
        var ids = data.Provinces.Select(p => p.Id).ToHashSet();

        foreach (var edge in data.Adjacencies)
        {
            ids.Should().Contain(edge.ProvinceAId,
                "every adjacency must reference a province in the same map");
            ids.Should().Contain(edge.ProvinceBId,
                "every adjacency must reference a province in the same map");
        }
    }

    [Fact]
    public void Load_GraphIsFullyConnected()
    {
        // No isolated components allowed. The build script verifies this and
        // patches with sea crossings (e.g. HI↔CA, AK↔Canada West) where
        // necessary; this test is the runtime safety net so a future map
        // refresh can't ship a disconnected graph silently.
        var data = MapSeeder.Load();
        var adj = new Dictionary<Guid, List<Guid>>();
        foreach (var p in data.Provinces) adj[p.Id] = new List<Guid>();
        foreach (var e in data.Adjacencies)
        {
            adj[e.ProvinceAId].Add(e.ProvinceBId);
            adj[e.ProvinceBId].Add(e.ProvinceAId);
        }

        var seen = new HashSet<Guid>();
        var queue = new Queue<Guid>();
        queue.Enqueue(data.Provinces[0].Id);
        while (queue.Count > 0)
        {
            var cur = queue.Dequeue();
            if (!seen.Add(cur)) continue;
            foreach (var n in adj[cur]) queue.Enqueue(n);
        }

        seen.Count.Should().Be(data.Provinces.Count,
            "every province must be reachable from every other (modulo future ocean theatres)");
    }

    [Fact]
    public void Load_ProducesDeterministicGuidsAcrossCalls()
    {
        // Re-running the migration on a fresh DB must produce the same PKs
        // every time. We're not running the migration here, but the Guid
        // derivation must be stable across calls.
        var first = MapSeeder.Load();
        var second = MapSeeder.Load();

        first.Provinces.Select(p => p.Id)
            .Should().Equal(second.Provinces.Select(p => p.Id));
    }
}
