// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarsAndSteel.Data;

#nullable disable

namespace StarsAndSteel.Data.Migrations
{
    [DbContext(typeof(StarsAndSteelDbContext))]
    [Migration("20260512120850_AddChatScopeAndQuietHours")]
    partial class AddChatScopeAndQuietHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.AiMemory", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("AiMemories");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConstructedAtTick")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FromPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ToPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromPlayerId");

                    b.HasIndex("ToPlayerId");

                    b.HasIndex("GameWorldId", "SentAtUtc");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ConstructionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IssuedAtTick")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TicksRemaining")
                        .HasColumnType("int");

                    b.Property<string>("UnitType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerPlayerId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("GameWorldId", "Status", "IssuedAtTick");

                    b.ToTable("ConstructionOrders");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.DiplomaticRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LastChangedAtTick")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ToPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrustScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromPlayerId");

                    b.HasIndex("ToPlayerId");

                    b.HasIndex("GameWorldId", "FromPlayerId");

                    b.ToTable("DiplomaticRelations");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.GameWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentTick")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MapSeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NextTickDueUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RngState")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TickIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.HasKey("Id");

                    b.ToTable("GameWorlds");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RelatedPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("Tick")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPlayerId");

                    b.HasIndex("GameWorldId", "Tick")
                        .IsDescending(false, true);

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiPersonality")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Electronics")
                        .HasColumnType("bigint");

                    b.Property<string>("FlagPrimaryHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("FlagSecondaryHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<long>("Food")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<long>("Manpower")
                        .HasColumnType("bigint");

                    b.Property<long>("Money")
                        .HasColumnType("bigint");

                    b.Property<string>("NationName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("Oil")
                        .HasColumnType("bigint");

                    b.Property<long>("Steel")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameWorldId", "IsAi");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasePopulation")
                        .HasColumnType("int");

                    b.Property<float>("CenterX")
                        .HasColumnType("real");

                    b.Property<float>("CenterY")
                        .HasColumnType("real");

                    b.Property<int>("ElectronicsPerTick")
                        .HasColumnType("int");

                    b.Property<int>("FoodPerTick")
                        .HasColumnType("int");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCoastal")
                        .HasColumnType("bit");

                    b.Property<int>("ManpowerPerTick")
                        .HasColumnType("int");

                    b.Property<int>("MoneyPerTick")
                        .HasColumnType("int");

                    b.Property<int>("MoraleLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OilPerTick")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SteelPerTick")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GameWorldId");

                    b.HasIndex("OwnerPlayerId");

                    b.HasIndex("GameWorldId", "OwnerPlayerId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ProvinceAdjacency", b =>
                {
                    b.Property<Guid>("ProvinceAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvinceBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSeaCrossing")
                        .HasColumnType("bit");

                    b.Property<float>("TerrainCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.HasKey("ProvinceAId", "ProvinceBId");

                    b.HasIndex("ProvinceBId");

                    b.ToTable("ProvinceAdjacencies");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ResearchProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProgressPoints")
                        .HasColumnType("int");

                    b.Property<string>("TechId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "TechId")
                        .IsUnique();

                    b.ToTable("ResearchProgress");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.TreatyOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpiresAtTick")
                        .HasColumnType("int");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProposedAtTick")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiverPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ResolvedAtTick")
                        .HasColumnType("int");

                    b.Property<Guid>("SenderPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverPlayerId");

                    b.HasIndex("SenderPlayerId");

                    b.HasIndex("GameWorldId", "ReceiverPlayerId", "Status");

                    b.HasIndex("GameWorldId", "Status", "ExpiresAtTick");

                    b.ToTable("TreatyOffers");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeBaseProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInTransit")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LocationProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Morale")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("TransitArrivalTick")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransitFromProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransitToProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("HomeBaseProvinceId");

                    b.HasIndex("LocationProvinceId");

                    b.HasIndex("OwnerPlayerId");

                    b.HasIndex("TransitFromProvinceId");

                    b.HasIndex("TransitToProvinceId");

                    b.HasIndex("GameWorldId", "OwnerPlayerId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.UnitOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IssuedAtTick")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("TargetProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetProvinceId");

                    b.HasIndex("UnitId");

                    b.HasIndex("Status", "IssuedAtTick");

                    b.ToTable("UnitOrders");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("QuietHoursEndUtc")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("QuietHoursStartUtc")
                        .HasColumnType("time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.AiMemory", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Player", "Player")
                        .WithOne("AiMemory")
                        .HasForeignKey("StarsAndSteel.Core.Entities.AiMemory", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Building", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Province", "Province")
                        .WithMany("Buildings")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Player", "FromPlayer")
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany()
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "ToPlayer")
                        .WithMany()
                        .HasForeignKey("ToPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromPlayer");

                    b.Navigation("GameWorld");

                    b.Navigation("ToPlayer");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ConstructionOrder", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany()
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "OwnerPlayer")
                        .WithMany()
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GameWorld");

                    b.Navigation("OwnerPlayer");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.DiplomaticRelation", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Player", "FromPlayer")
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany()
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "ToPlayer")
                        .WithMany()
                        .HasForeignKey("ToPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromPlayer");

                    b.Navigation("GameWorld");

                    b.Navigation("ToPlayer");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.NewsItem", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany("NewsItems")
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "RelatedPlayer")
                        .WithMany()
                        .HasForeignKey("RelatedPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GameWorld");

                    b.Navigation("RelatedPlayer");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Player", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany("Players")
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameWorld");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Province", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany("Provinces")
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "OwnerPlayer")
                        .WithMany("OwnedProvinces")
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GameWorld");

                    b.Navigation("OwnerPlayer");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ProvinceAdjacency", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Province", "ProvinceA")
                        .WithMany()
                        .HasForeignKey("ProvinceAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Province", "ProvinceB")
                        .WithMany()
                        .HasForeignKey("ProvinceBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProvinceA");

                    b.Navigation("ProvinceB");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.ResearchProgress", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.TreatyOffer", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany()
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "ReceiverPlayer")
                        .WithMany()
                        .HasForeignKey("ReceiverPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "SenderPlayer")
                        .WithMany()
                        .HasForeignKey("SenderPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GameWorld");

                    b.Navigation("ReceiverPlayer");

                    b.Navigation("SenderPlayer");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Unit", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.GameWorld", "GameWorld")
                        .WithMany()
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Province", "HomeBaseProvince")
                        .WithMany()
                        .HasForeignKey("HomeBaseProvinceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StarsAndSteel.Core.Entities.Province", "LocationProvince")
                        .WithMany("UnitsStationed")
                        .HasForeignKey("LocationProvinceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StarsAndSteel.Core.Entities.Player", "OwnerPlayer")
                        .WithMany("OwnedUnits")
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StarsAndSteel.Core.Entities.Province", "TransitFromProvince")
                        .WithMany()
                        .HasForeignKey("TransitFromProvinceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StarsAndSteel.Core.Entities.Province", "TransitToProvince")
                        .WithMany()
                        .HasForeignKey("TransitToProvinceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GameWorld");

                    b.Navigation("HomeBaseProvince");

                    b.Navigation("LocationProvince");

                    b.Navigation("OwnerPlayer");

                    b.Navigation("TransitFromProvince");

                    b.Navigation("TransitToProvince");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.UnitOrder", b =>
                {
                    b.HasOne("StarsAndSteel.Core.Entities.Province", "TargetProvince")
                        .WithMany()
                        .HasForeignKey("TargetProvinceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StarsAndSteel.Core.Entities.Unit", "Unit")
                        .WithMany("Orders")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetProvince");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.GameWorld", b =>
                {
                    b.Navigation("NewsItems");

                    b.Navigation("Players");

                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Player", b =>
                {
                    b.Navigation("AiMemory");

                    b.Navigation("OwnedProvinces");

                    b.Navigation("OwnedUnits");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Province", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("UnitsStationed");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.Unit", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("StarsAndSteel.Core.Entities.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
